In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Global_Superstore.csv to Global_Superstore (1).csv

In [ ]:
df = pd.read_csv("Global_Superstore.csv")

In [ ]:
df.head()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,Region,Country,City,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,CA-2024-1001,2024-02-02,2024-02-05,CUST-0001,Customer 1,Home Office,East,India,City 2,Furniture,SubCat 2,3720.67,4,0.07,683.77
1,CA-2024-1002,2024-03-03,2024-03-06,CUST-0002,Customer 2,Home Office,East,India,City 3,Technology,SubCat 3,2138.51,1,0.03,79.19
2,CA-2024-1003,2024-04-04,2024-04-07,CUST-0003,Customer 3,Home Office,East,India,City 4,Technology,SubCat 4,1034.25,9,0.13,339.05
3,CA-2024-1004,2024-05-05,2024-05-08,CUST-0004,Customer 4,Corporate,East,India,City 5,Furniture,SubCat 5,3505.79,6,0.08,58.38
4,CA-2024-1005,2024-06-06,2024-06-09,CUST-0005,Customer 5,Corporate,East,India,City 6,Furniture,SubCat 6,1930.64,6,0.25,524.47

In [ ]:
df.tail()

,Order ID,Order Date,Ship Date,Customer ID,Customer Name,Segment,Region,Country,City,Category,Sub-Category,Sales,Quantity,Discount,Profit
198,CA-2024-1199,2024-08-04,2024-08-07,CUST-0199,Customer 199,Home Office,West,India,City 20,Office Supplies,SubCat 10,1787.94,3,0.07,-24.27
199,CA-2024-1200,2024-09-05,2024-09-08,CUST-0200,Customer 200,Consumer,West,India,City 1,Technology,SubCat 1,806.71,2,0.05,727.42
200,CA-2024-1001,2024-02-02,2024-02-05,CUST-0001,Customer 1,Home Office,East,India,City 2,Furniture,SubCat 2,3720.67,4,0.07,683.77
201,CA-2024-1002,2024-03-03,2024-03-06,CUST-0002,Customer 2,Home Office,East,India,City 3,Technology,SubCat 3,2138.51,1,0.03,79.19
202,CA-2024-1003,2024-04-04,2024-04-07,CUST-0003,Customer 3,Home Office,East,India,City 4,Technology,SubCat 4,1034.25,9,0.13,339.05

In [ ]:
df.shape

(203, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203 entries, 0 to 202
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order ID       203 non-null    object
 1   Order Date     203 non-null    object
 2   Ship Date      203 non-null    object
 3   Customer ID    203 non-null    object
 4   Customer Name  203 non-null    object
 5   Segment        203 non-null    object
 6   Region         202 non-null    object
 7   Country        203 non-null    object
 8   City           203 non-null    object
 9   Category       203 non-null    object
 10  Sub-Category   203 non-null    object
 11  Sales          202 non-null    float64
 12  Quantity       203 non-null    int64
 13  Discount       203 non-null    float64
 14  Profit         202 non-null    float64
dtypes: float64(3), int64(1), object(11)
memory usage: 23.9+ KB

In [ ]:
# Check Missing Values
print(df.isnull().sum())

# Handle Missing Values
df['Sales'] = df['Sales'].fillna(df['Sales'].mean())
df['Profit'] = df['Profit'].fillna(df['Profit'].mean())
df['Region'] = df['Region'].fillna(df['Region'].mode()[0])

#Check Duplicate Rows
print(df.isnull().sum())

print("Duplicates:", df.duplicated().sum())
# Remove Duplicates
df = df.drop_duplicates()

# Convert dates
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

print(df.describe())

print("Total Sales =", df['Sales'].sum())
print("Total Profit =", df['Profit'].sum())

# Eport cleaned dataset
df.to_csv('Cleaned_Global_Superstore.csv', index=False)

files.download('Cleaned_Global_Superstore.csv')

Order ID         0
Order Date       0
Ship Date        0
Customer ID      0
Customer Name    0
Segment          0
Region           0
Country          0
City             0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
Year             0
Month            0
Day              0
Quarter          0
dtype: int64
Order ID         0
Order Date       0
Ship Date        0
Customer ID      0
Customer Name    0
Segment          0
Region           0
Country          0
City             0
Category         0
Sub-Category     0
Sales            0
Quantity         0
Discount         0
Profit           0
Year             0
Month            0
Day              0
Quarter          0
dtype: int64
Duplicates: 0
                Order Date            Ship Date        Sales    Quantity  \
count                  200                  200   200.000000  200.000000
mean   2024-06-28 09:21:36  2024-06-28 10:48:00  2516.753489    5.385000
min    2024-01-01 00:00:00  2024-01-04 00:00:00    88.260000    1.000000
25%    2024-04-02 00:00:00  2024-04-01 00:00:00  1238.762500    3.000000
50%    2024-06-26 00:00:00  2024-06-25 00:00:00  2410.380000    5.000000
75%    2024-09-22 00:00:00  2024-09-25 00:00:00  3741.500000    8.000000
max    2024-12-28 00:00:00  2024-12-27 00:00:00  4927.280000   10.000000
std                    NaN                  NaN  1437.327666    2.947919

         Discount      Profit    Year       Month         Day     Quarter
count  200.000000  200.000000   200.0  200.000000  200.000000  200.000000
mean     0.139200  425.791005  2024.0    6.460000   14.280000    2.485000
min      0.000000 -183.020000  2024.0    1.000000    1.000000    1.000000
25%      0.070000  129.650000  2024.0    3.750000    7.000000    1.750000
50%      0.135000  461.910000  2024.0    6.000000   14.000000    2.000000
75%      0.210000  686.205000  2024.0    9.000000   21.000000    3.000000
max      0.300000  988.040000  2024.0   12.000000   28.000000    4.000000
std      0.086631  338.765277     0.0    3.427409    8.165475    1.111735
Total Sales = 503350.6978712872
Total Profit = 85158.20100502513